export const SCHOOLS = [
    "Alcott Elementary",
    "Audubon Elementary",
    "Bell Elementary",
    "Blackwell Elementary",
    "Carson Elementary",
    "Clara Barton Elementary",
    "Community School",
    "Dickinson Elementary",
    "Discovery Elementary",
    "Einstein Elementary",
    "Ella Baker Elementary",
    "Emerson K-12",
    "Explorer Community School",
    "Franklin Elementary",
    "Frost Elementary",
    "Juanita Elementary",
    "Keller Elementary",
    "Kirk Elementary",
    "Lakeview Elementary",
    "Mann Elementary",
    "McAuliffe Elementary",
    "Mead Elementary",
    "Muir Elementary",
    "Redmond Elementary",
    "Rockwell Elementary",
    "Rosa Parks Elementary",
    "Rose Hill Elementary",
    "Rush Elementary",
    "Sandburg Elementary",
    "Smith Elementary",
    "Thoreau Elementary",
    "Twain Elementary",
    "Wilder Elementary",
    "Environmental Middle",
    "Evergreen Middle",
    "Finn Hill Middle",
    "Inglewood Middle",
    "Kamiakin Middle",
    "Kirkland Middle",
    "Northstar Middle",
    "Redmond Middle",
    "Renaissance Middle",
    "Rose Hill Middle",
    "Stella Schola Middle",
    "Timberline Middle",
    "Eastlake High",
    "Emerson High",
    "Futures School",
    "International",
    "Juanita High",
    "Lake Washington High",
    "Redmond High",
    "Tesla STEM High",
    "WANIC High"
];
