export const SCHOOLS = [
    'Keller Elementary',
    'Juanita Elementary',
    'Twain Elementary',
    'Rush Elementary',
    'McAuliffe Elementary',
    'Bell Elementary',
    'Alcott Elementary',
    'Kirk Elementary',
    'Einstein Elementary',
    'Rockwell Elementary',
    'Rose Hill Elementary',
    'Franklin Elementary',
    'Dickinson Elementary',
    'Thoreau Elementary',
    'Summer School',
    'Sandburg Elementary',
    'Redmond Elementary',
    'Baker Elementary',
    'Barton Elementary',
    'Smith Elementary',
    'Muir Elementary',
    'Carson Elementary',
    'Wilder Elementary',
    'Mead Elementary',
    'Special Services',
    'Lakeview Elementary',
    'Rosa Parks Elementary',
    'Audubon Elementary',
    'Mann Elementary',
    'Discovery Elementary',
    'Frost Elementary',
    'Blackwell Elementary',
    'Community School',
    'Explorer Elementary',
    'Emerson K-12',
    'Contractual School',
    'Environmental',
    'Timberline Middle School',
    'Redmond Middle School',
    'Rose Hill Middle School',
    'Finn Hill Middle School',
    'Kamiakin Middle School',
    'Evergreen Middle School',
    'Kirkland Middle School',
    'Inglewood Middle School',
    'International',
    'Stella Schola',
    'Northstar Middle School',
    'Renaissance',
    'Eastlake High School',
    'WaNIC Summer School',
    'Redmond High School',
    'Lake Washington High School',
    'STEM School',
    'Emerson High School',
    'WaNIC Skill Center',
    'WaNIC Skill Center',
    'WaNIC Summer School',
    'Futures School'
];
